config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /end_user/sign_in ...
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search", as: 'search'
  get "search_confirm" => "searches#search_confirm", as: 'search_confirm'



  scope module: :public do
   root to: "homes#top"
   get 'homes/about' => 'homes#about', as: 'about'
   get 'end_user/my_profile' => 'end_users#my_profile', as: 'my_profile'
   get 'end_user/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
   patch 'end_user/withdraw' => 'end_users#withdraw', as: 'withdraw'

   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
     get 'confirm'
    end
   end

   resources :themas, only: [:update, :create, :edit, :index, :destroy, :new] do
    member do
     post 'participant' => 'participants#participant', as: 'participant'
     patch 'unparticipant' => 'participants#unparticipant', as: 'unparticipant'
     patch 'rejoin' => 'participants#rejoin', as: 'rejoin'
    end
   end

   resources :rooms, only: [:create, :show]
   resources :chats, only: [:create]

   resources :end_users, only: [:update, :create, :edit, :show] do
    member do
     get :follows, :followers
    end
    resources :relationships, only: [:create, :destroy, :index]
    member do
     get :likes
    end
   end

  end

  namespace :admin do
   resources :posts, only: [:show]
   resources :end_users, only: [:index, :show, :edit, :update]
   resources :comments, only: [:destroy]
   get "search" => "searches#search", as: 'search'
   get 'homes/top' => "homes#top", as: 'top'
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :post
  validates :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  def destroy
   @comment = Comment.find(params[:id])
   @post = @comment.post
   @comment.destroy!
   flash.now[:alert] = '投稿を削除しました'
   #renderしたときに@postのデータがないので@postを定義
  end

end

app/helpers/admin/comment_helper.rb
module Admin::CommentHelper
end

app/views/admin/comments/_post_comments.html.erb
<% if @post.comments.present? %>
 <p>コメント件数：<%= @post.comments.count %></p>
  <% @post.comments.each do |comment| %>
  <div class="comment">
   <span class="mr-2"><%= comment.end_user.name %></span>
   <%= comment.created_at.strftime('%Y/%m/%d') %></br>
   <%= comment.comment %>
    <div class="comment-delete">
     <%= link_to "削除", admin_comment_path(comment.id), method: :delete, remote: true, data: {confirm: "本当に削除しますか？"} %>
    </div>
  </div>
  <% end %>
<% else %>
  <p>コメントはまだありません</p>
<% end %>

app/views/admin/comments/destroy.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'admin/comments/post_comments', post: @post) %>");
<!--エラーメッセージ-->
$('#flash-message').html("<%= j(render 'layouts/flash') %>");