config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /end_user/sign_in ...
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search", as: 'search'
  get "search_confirm" => "searches#search_confirm", as: 'search_confirm'



  scope module: :public do
   root to: "homes#top"
   get 'homes/about' => 'homes#about', as: 'about'
   get 'end_user/my_profile' => 'end_users#my_profile', as: 'my_profile'
   get 'end_user/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
   patch 'end_user/withdraw' => 'end_users#withdraw', as: 'withdraw'

   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
     get 'confirm'
    end
   end

   resources :themas, only: [:update, :create, :edit, :index, :destroy, :new] do
    member do
     post 'participant' => 'participants#participant', as: 'participant'
     patch 'unparticipant' => 'participants#unparticipant', as: 'unparticipant'
     patch 'rejoin' => 'participants#rejoin', as: 'rejoin'
    end
   end

   resources :rooms, only: [:create, :show]
   resources :chats, only: [:create]

   resources :end_users, only: [:update, :create, :edit, :show] do
    member do
     get :follows, :followers
    end
    resources :relationships, only: [:create, :destroy, :index]
    member do
     get :likes
    end
   end

  end

  namespace :admin do
   resources :posts, only: [:show]
   resources :end_users, only: [:index, :show, :edit, :update]
   resources :comments, only: [:destroy]
   get "search" => "searches#search", as: 'search'
   get 'homes/top' => "homes#top", as: 'top'
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
   # 投稿内容全てを作成日時の降順に並び替えて表示する（新着順）
   @posts = Post.published.order("created_at DESC").page(params[:page]).per(10)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<main class="container">

 <div class="row justify-content-center m-3">
   <h3>投稿一覧</h3>
 </div>

 <div class="search_form m-3 row justify-content-center">
   <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
   <%= f.text_field :search %>
   <%= f.submit "検索", class: "btn btn-primary" %>
   <% end %>
 </div>

 <div class="row">

  <%#= 検索内容がpostだった時 %>
  <% if !@posts.nil? %>
   <% @posts.each do |post| %>
   <div class="col-md-3">
    <%= link_to admin_post_path(post.id), class: "text-dark" do %>
     <%= image_tag attachment_url(post, :picture), size: "200x150" %>
    <% end %>
    <p><%= post.content %></p>
   </div>
   <% end %>
  <% end %>

  <%#= 検索内容がtagだった時 %>
  <% if !@tags.nil? %>
   <% @tags.each do |tag| %>
   <div class="col-md-3">
    <p><%= tag.tag_name %></p>
   </div>
   <% end %>
  <% end %>

  <%#= 検索内容がend_userだった時 %>
  <% if !@end_users.nil? %>
   <% @end_users.each do |end_user| %>
   <div class="col-md-3">
    <p><%= end_user.name %></p>
   </div>
   <% end %>
  <% end %>

 </div>
 
 <%= paginate @posts %>

</main>