config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /end_user/sign_in ...
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search", as: 'search'
  get "search_confirm" => "searches#search_confirm", as: 'search_confirm'



  scope module: :public do
   root to: "homes#top"
   get 'homes/about' => 'homes#about', as: 'about'
   get 'end_user/my_profile' => 'end_users#my_profile', as: 'my_profile'
   get 'end_user/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
   patch 'end_user/withdraw' => 'end_users#withdraw', as: 'withdraw'

   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
     get 'confirm'
    end
   end

   resources :themas, only: [:update, :create, :edit, :index, :destroy, :new] do
    member do
     post 'participant' => 'participants#participant', as: 'participant'
     patch 'unparticipant' => 'participants#unparticipant', as: 'unparticipant'
     patch 'rejoin' => 'participants#rejoin', as: 'rejoin'
    end
   end

   resources :rooms, only: [:create, :show]
   resources :chats, only: [:create]

   resources :end_users, only: [:update, :create, :edit, :show] do
    member do
     get :follows, :followers
    end
    resources :relationships, only: [:create, :destroy, :index]
    member do
     get :likes
    end
   end

  end

  namespace :admin do
   resources :posts, only: [:show]
   resources :end_users, only: [:index, :show, :edit, :update]
   resources :comments, only: [:destroy]
   get "search" => "searches#search", as: 'search'
   get 'homes/top' => "homes#top", as: 'top'
  end

end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum sex: { man: 0, female: 1, non_binary: 2 }

  has_one_attached :profile_image, dependent: :destroy

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [100, 100]).processed
  end

  def self.guest_sign_in
    # EndUserの中から(name: "guest", email: 'guest@example.com', sex: "non_binary")に当てはまるアカウントがあればそれを取り出す
    # もし、当てはまることがなければ新規にアカウントを作成してend_userに代入する
    EndUser.find_or_create_by!(name: "guest", email: 'guest@example.com', sex: "non_binary") do |end_user|
      # end_userのpasswordにランダムで作成したパスワードを設定する
      end_user.password = SecureRandom.urlsafe_base64
    end
  end

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :end_user_rooms
  has_many :rooms, through: :end_user_rooms
  has_many :chats, dependent: :destroy
  has_many :themas
  has_many :participants
  has_many :themas, through: :participants

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # following_end_user:中間テーブルを通してfollowedモデルのフォローされる側を取得すること
  has_many :following_end_user, through: :follower, source: :followed # 自分がフォローしている人
  # follower_end_user:中間テーブルを通してfollowerモデルのフォローする側を取得すること
  has_many :follower_end_user, through: :followed, source: :follower # 自分をフォローしている人

  #ユーザーが投稿に対して既にいいねしているか判定する
  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  # タグとユーザーと投稿記事をまとめて曖昧検索する
  def self.search(search)
    if search != nil
      EndUser.where('name LIKE(?)', "%#{search}%")
    else
      EndUser.all
    end
  end

  # ユーザーをフォローする
  def follow(end_user_id)
    follower.create(followed_id: end_user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(end_user_id)
    follower.find_by(followed_id: end_user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(end_user)
    following_end_user.include?(end_user)
  end

  # お互いにフォローしているか判定
  def matching
   following_end_user & follower_end_user
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController

  def index
   @end_users = EndUser.all
  end

  def show
   # URLの末尾に記載されたidを取得して、そのidに該当するPostモデルのデータを取得する
   @end_user = EndUser.find(params[:id])
  end

  def edit
   # URLの末尾に記載されたidを取得して、そのidに該当するPostモデルのデータを取得する
   @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(current_end_user_params)
       redirect_to admin_end_user_path(@end_user.id)
    else
       render :update
    end
  end

  private

  def current_end_user_params
      params.require(:end_user).permit(:name, :sex, :self_introduction, :email, :profile_image, :is_deleted)
  end

end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<main class="container">
 <div class="row">

  <div class="col-7 m-3">
   <h4 class="mt-5">プロフィール編集</h4>
     <%= form_with model: @end_user, url: admin_end_user_path(@end_user.id) do |f| %>
     <table class="d-flex justify-content-center">
      <tr>
       <td>
        <p class="mt-4">
         <%= f.label :profile_image, "プロフィール画像" %>
        </p>
       </td>
       <td><%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %></td>
      </tr>
      <tr>
       <td>
        <p class="m-2"><%= f.label :email, "メールアドレス" %></p>
       </td>
       <td>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
       </td>
      </tr>
      <tr>
       <td>
        <p class="m-2"><%= f.label :name, "ユーザー名" %></p>
       </td>
       <td>
        <%= f.text_field :name %>
       </td>
      </tr>
      <tr>
       <td>
        <p class="m-2"><%= f.label :sex, "性別" %></p>
       </td>
       <td>
        <%= f.radio_button :sex, "man" %>
        <%= f.label :sex, "男性", {value: 0, style: "display: inline-block;"} %>
        <%= f.radio_button :sex, "female" %>
        <%= f.label :sex, "女性", {value: 1, style: "display: inline-block;"} %>
        <%= f.radio_button :sex, "non_binary" %>
        <%= f.label :sex, "X", {value: 2, style: "display: inline-block;"} %>
       </td>
      </tr>
      <tr>
       <td>
        <p class="m-2"><%= f.label :self_introduction, "自己紹介" %></p>
       </td>
       <td>
         <%= f.text_area :self_introduction %>
       </td>
      </tr>
      <tr>
       <td><p class="m-3"><%= f.label :is_deleted, "ステータス" %></p></td>
       <td>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, "無効", {value: true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, "有効", {value: false, style: "display: inline-block;"} %>
       </td>
      </tr>
      <tr>
       <td></td>
       <td><%= f.submit "変更", class: 'btn btn-primary btn-sm' %></td>
      </tr>
     </table>
     <% end %>
  </div>

 </div>
</main>

app/views/admin/end_users/index.html.erb
<main class="container">
 <div class="row">
  <div class="col-12">
   <h4 class="m-5">会員一覧</h4>
  </div>
 
 <div class="col-12 m-3 d-flex justify-content-start">
  <table class="table">
   <thead class="table-active">
     <th>会員ID</th>
     <th>氏名</th>
     <th>メールアドレス</th>
     <th>ステータス</th>
   </thead>
   <tbody>
   <% @end_users.each do |end_user| %>
    <tr>
     <td><%= end_user.id %></td>
     <td>
      <%= link_to admin_end_user_path(end_user.id), class: "text-dark" do %>
       <%= end_user.name %>
      <% end %>
     </td>
     <td><%= end_user.email %></td>
     <td>
      <% if end_user.is_deleted %>
        <p class="text-muted">退会</p>
      <% else %>
        <p class="text-success">有効</p>
      <% end %>
     </td>
    </tr>
   <% end %>
   </tbody>
  </table>
 </div>
 
</main>

app/views/admin/end_users/show.html.erb
<main class="container">
 <div class="row">
  <div class="col-md-3  d-flex justify-content-around">
  <h5 class="m-5">プロフィール</h5>
  </div>
 </div>

 <div class="row">
  <div class="col-md-3 m-3 d-flex justify-content-around">
   <h5>登録情報</h5>
   <%= link_to "編集する", edit_admin_end_user_path(@end_user.id), class: 'btn btn-success btn-sm' %>
  </div>
 </div>

 <div class="col-md-8 m-3">
  <table class="table table-bordered">
   <tbody>
    <tr>
     <td class="table-active">プロフィール画像</td>
     <td><%= image_tag @end_user.get_profile_image %></td>
    </tr>
    <tr>
     <td class="table-active">ユーザー名</td>
     <td><%= @end_user.name %></td>
    <tr>
    <tr>
     <td class="table-active">性別</td>
     <td><%= @end_user.sex_i18n %></td>
    <tr>
    <tr>
     <td class="table-active">自己紹介</td>
     <td><%= @end_user.self_introduction %></td>
    <tr>
    <tr>
     <td class="table-active">メールアドレス</td>
     <td><%= @end_user.email %></td>
    <tr>
    <tr>
     <td class="table-active">ステータス</td>
     <td>
      <% if @end_user.is_deleted %>
        <p class="text-muted">退会</p>
      <% else %>
        <p class="text-success">有効</p>
      <% end %>
     </td>
    <tr>
   <tbody>
  </table>
 </div>
</main>