config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /end_user/sign_in ...
  devise_for :end_users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search", as: 'search'
  get "search_confirm" => "searches#search_confirm", as: 'search_confirm'



  scope module: :public do
   root to: "homes#top"
   get 'homes/about' => 'homes#about', as: 'about'
   get 'end_user/my_profile' => 'end_users#my_profile', as: 'my_profile'
   get 'end_user/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe'
   patch 'end_user/withdraw' => 'end_users#withdraw', as: 'withdraw'

   resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
     get 'confirm'
    end
   end

   resources :themas, only: [:update, :create, :edit, :index, :destroy, :new] do
    member do
     post 'participant' => 'participants#participant', as: 'participant'
     patch 'unparticipant' => 'participants#unparticipant', as: 'unparticipant'
     patch 'rejoin' => 'participants#rejoin', as: 'rejoin'
    end
   end

   resources :rooms, only: [:create, :show]
   resources :chats, only: [:create]

   resources :end_users, only: [:update, :create, :edit, :show] do
    member do
     get :follows, :followers
    end
    resources :relationships, only: [:create, :destroy, :index]
    member do
     get :likes
    end
   end

  end

  namespace :admin do
   resources :posts, only: [:show]
   resources :end_users, only: [:index, :show, :edit, :update]
   resources :comments, only: [:destroy]
   get "search" => "searches#search", as: 'search'
   get 'homes/top' => "homes#top", as: 'top'
  end

end

app/views/layouts/_error_messages.html.erb
<!--エラーメッセージ-->
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= object.errors.count %>件のエラー</h5>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<!--エラーメッセージ-->
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Shumitomo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-100">
    <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to root_path , class: "navbar-brand" do %>
     <%= image_tag 'logo_transparent.png', size: '150x150' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav ml-auto">
      <% if end_user_signed_in? %> <%#if 条件1%>
          <%#処理1   条件1がtrueだったら処理1を行う%>
      <li class="nav-item mr-5">
        <p>ようこそ、<%= current_end_user.name %>さん！</p>
      </li>
      <li class="nav-item mr-5">
        <%= link_to my_profile_path, class: "nav-link text-dark" do %>
         プロフィール
        <% end %>
      </li>
       <li class="nav-item mr-5">
        <%= link_to themas_path, class: "nav-link text-dark" do %>
         お題一覧
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to posts_path, class: "nav-link text-dark" do %>
         投稿一覧
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to confirm_posts_path, class: "nav-link text-dark" do %>
         下書き一覧
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to destroy_end_user_session_path, method: :delete, class: "nav-link text-dark" do %>
         ログアウト
        <% end %>
      </li>
      <% elsif admin_signed_in? %> <%#elsif 条件2%>
          <%#処理2  条件1がfalse、かつ条件2がtrueだったら処理2を行う%>
      <li class="nav-item mr-5">
        <%= link_to admin_end_users_path, class: "nav-link text-dark" do %>
         会員一覧
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to admin_top_path, class: "nav-link text-dark" do %>
         投稿一覧
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-dark" do %>
         ログアウト
        <% end %>
      </li>
      <% else %><%#else処理x%>
          <%#処理x 条件1～条件nが全てfalseだったら処理xを行う%>
      <li class="nav-item mr-5">
        <%= link_to about_path, class: "nav-link text-dark" do %>
         About
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to posts_path, class: "nav-link text-dark" do %>
         投稿一覧
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to new_end_user_registration_path, class: "nav-link text-dark" do %>
         新規登録
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to end_user_session_path, class: "nav-link text-dark" do %>
         ログイン
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <%= link_to end_users_guest_sign_in_path, method: :post, class: "nav-link text-dark" do %>
         ゲストログイン（閲覧用）
        <% end %>
      </li>
      <% end %>
     </ul>
    </div>

    </header>

    <main>
     <!--フラッシュメッセージの部分をdivタグで囲む-->
     <div id="flash-message">
      <%= render 'layouts/flash' %>
     </div>
     <%= yield %>
    </main>

    <footer class="text-center text-lg-start bg-white text-muted">
     <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
       <p> 2022 shumitomo </p>
     </div>
    </footer>

  </body>
</html>